// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"time"
)

type Akun struct {
	ID         int64     `json:"id"`
	Nama       string    `json:"nama"`
	Saldo      int64     `json:"saldo"`
	DibuatPada time.Time `json:"dibuat_pada"`
}

type Catatan struct {
	ID     int64 `json:"id"`
	IDAkun int64 `json:"id_akun"`
	// bisa positif bisa negatif
	Jumlah     int64     `json:"jumlah"`
	DibuatPada time.Time `json:"dibuat_pada"`
}

type Transfer struct {
	ID       int64 `json:"id"`
	Pengirim int64 `json:"pengirim"`
	Penerima int64 `json:"penerima"`
	// harus positif
	Jumlah     int64     `json:"jumlah"`
	DibuatPada time.Time `json:"dibuat_pada"`
}
