// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"context"
)

type Querier interface {
	ChangeSaldo(ctx context.Context, arg ChangeSaldoParams) (Akun, error)
	CreateAkun(ctx context.Context, arg CreateAkunParams) (Akun, error)
	CreateCatatan(ctx context.Context, arg CreateCatatanParams) (Catatan, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	DeleteAkun(ctx context.Context, id int64) error
	GetAkun(ctx context.Context, id int64) (Akun, error)
	GetAkunForUpdate(ctx context.Context, id int64) (Akun, error)
	GetCatatan(ctx context.Context, id int64) (Catatan, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	ListAkun(ctx context.Context, arg ListAkunParams) ([]Akun, error)
	ListCatatan(ctx context.Context, arg ListCatatanParams) ([]Catatan, error)
	UpdateAkun(ctx context.Context, arg UpdateAkunParams) (Akun, error)
}

var _ Querier = (*Queries)(nil)
